//
//  Moods.swift
//  MoodTracker
//
//  Created by Alex Wayne on 11/6/"Powerful""Powerful".
//

import Foundation

let Moods: [Mood] = [
    Mood(name: "Sad", section: "Sad"),
    Mood(name: "Guilty", section: "Sad"),
    Mood(name: "Bashful", section: "Sad"),
    Mood(name: "Ashamed", section: "Sad"),
    Mood(name: "Stupid", section: "Sad"),
    Mood(name: "Depressed", section: "Sad"),
    Mood(name: "Miserable", section: "Sad"),
    Mood(name: "Lonely", section: "Sad"),
    Mood(name: "Inadequate", section: "Sad"),
    Mood(name: "Bored", section: "Sad"),
    Mood(name: "Inferior", section: "Sad"),
    Mood(name: "Sleepy", section: "Sad"),
    Mood(name: "Apathetic", section: "Sad"),
    Mood(name: "Peaceful", section: "Peaceful"),
    Mood(name: "Content", section: "Peaceful"),
    Mood(name: "Pensive", section: "Peaceful"),
    Mood(name: "Thoughtful", section: "Peaceful"),
    Mood(name: "Relaxed", section: "Peaceful"),
    Mood(name: "Intimate", section: "Peaceful"),
    Mood(name: "Responsive", section: "Peaceful"),
    Mood(name: "Loving", section: "Peaceful"),
    Mood(name: "Serene", section: "Peaceful"),
    Mood(name: "Loving", section: "Peaceful"),
    Mood(name: "Sentimental", section: "Peaceful"),
    Mood(name: "Trusting", section: "Peaceful"),
    Mood(name: "Thankful", section: "Peaceful"),
    Mood(name: "Nurturing", section: "Peaceful"),
    Mood(name: "Powerful", section: "Powerful"),
    Mood(name: "Faithful", section: "Powerful"),
    Mood(name: "Confident", section: "Powerful"),
    Mood(name: "Important", section: "Powerful"),
    Mood(name: "Intelligent", section: "Powerful"),
    Mood(name: "Hopeful", section: "Powerful"),
    Mood(name: "Worthwile", section: "Powerful"),
    Mood(name: "Appreciated", section: "Powerful"),
    Mood(name: "Valuable", section: "Powerful"),
    Mood(name: "Respected", section: "Powerful"),
    Mood(name: "Satisfied", section: "Powerful"),
    Mood(name: "Proud", section: "Powerful"),
    Mood(name: "Cheerful", section: "Powerful"),
    Mood(name: "Joyful", section: "Joyful"),
    Mood(name: "Aware", section: "Joyful"),
    Mood(name: "Delightful", section: "Joyful"),
    Mood(name: "Creative", section: "Joyful"),
    Mood(name: "Extravagent", section: "Joyful"),
    Mood(name: "Playful", section: "Joyful"),
    Mood(name: "Amused", section: "Joyful"),
    Mood(name: "Energetic", section: "Joyful"),
    Mood(name: "Stimulating", section: "Joyful"),
    Mood(name: "Vibrant", section: "Joyful"),
    Mood(name: "Fascinating", section: "Joyful"),
    Mood(name: "Excited", section: "Joyful"),
    Mood(name: "Daring", section: "Joyful"),
    Mood(name: "Scared", section: "Scared"),
    Mood(name: "Anxious", section: "Scared"),
    Mood(name: "Embarrassed", section: "Scared"),
    Mood(name: "Insecure", section: "Scared"),
    Mood(name: "Foolish", section: "Scared"),
    Mood(name: "Submissive", section: "Scared"),
    Mood(name: "Weak", section: "Scared"),
    Mood(name: "Helpless", section: "Scared"),
    Mood(name: "Insignificant", section: "Scared"),
    Mood(name: "Confused", section: "Scared"),
    Mood(name: "Discouraged", section: "Scared"),
    Mood(name: "Rejected", section: "Scared"),
    Mood(name: "Bewildered", section: "Scared"),
    Mood(name: "Mad", section: "Mad"),
    Mood(name: "Critical", section: "Mad"),
    Mood(name: "Skeptical", section: "Mad"),
    Mood(name: "Hateful", section: "Mad"),
    Mood(name: "Irritated", section: "Mad"),
    Mood(name: "Rage", section: "Mad"),
    Mood(name: "Furious", section: "Mad"),
    Mood(name: "Angry", section: "Mad"),
    Mood(name: "Frustrated", section: "Mad"),
    Mood(name: "Hostile", section: "Mad"),
    Mood(name: "Selfish", section: "Mad"),
    Mood(name: "Hurt", section: "Mad"),
    Mood(name: "Jealous", section: "Mad"),

]
