//
//  Moods.swift
//  MoodTracker
//
//  Created by Alex Wayne on 11/6/"Powerful""Powerful".
//

import Foundation

let Moods: [[String: String]] = [
    ["name": "Sad", "section": "Sad"],
    ["name": "Guilty", "section": "Sad"],
    ["name": "Bashful", "section": "Sad"],
    ["name": "Ashamed", "section": "Sad"],
    ["name": "Stupid", "section": "Sad"],
    ["name": "Depressed", "section": "Sad"],
    ["name": "Miserable", "section": "Sad"],
    ["name": "Lonely", "section": "Sad"],
    ["name": "Inadequate", "section": "Sad"],
    ["name": "Bored", "section": "Sad"],
    ["name": "Inferior", "section": "Sad"],
    ["name": "Sleepy", "section": "Sad"],
    ["name": "Apathetic", "section": "Sad"],
    ["name": "Peaceful", "section": "Peaceful"],
    ["name": "Content", "section": "Peaceful"],
    ["name": "Pensive", "section": "Peaceful"],
    ["name": "Thoughtful", "section": "Peaceful"],
    ["name": "Relaxed", "section": "Peaceful"],
    ["name": "Intimate", "section": "Peaceful"],
    ["name": "Responsive", "section": "Peaceful"],
    ["name": "Loving", "section": "Peaceful"],
    ["name": "Serene", "section": "Peaceful"],
    ["name": "Loving", "section": "Peaceful"],
    ["name": "Sentimental", "section": "Peaceful"],
    ["name": "Trusting", "section": "Peaceful"],
    ["name": "Thankful", "section": "Peaceful"],
    ["name": "Nurturing", "section": "Peaceful"],
    ["name": "Powerful", "section": "Powerful"],
    ["name": "Faithful", "section": "Powerful"],
    ["name": "Confident", "section": "Powerful"],
    ["name": "Important", "section": "Powerful"],
    ["name": "Intelligent", "section": "Powerful"],
    ["name": "Hopeful", "section": "Powerful"],
    ["name": "Worthwile", "section": "Powerful"],
    ["name": "Appreciated", "section": "Powerful"],
    ["name": "Valuable", "section": "Powerful"],
    ["name": "Respected", "section": "Powerful"],
    ["name": "Satisfied", "section": "Powerful"],
    ["name": "Proud", "section": "Powerful"],
    ["name": "Cheerful", "section": "Powerful"],
    ["name": "Joyful", "section": "Joyful"],
    ["name": "Aware", "section": "Joyful"],
    ["name": "Delightful", "section": "Joyful"],
    ["name": "Creative", "section": "Joyful"],
    ["name": "Extravagent", "section": "Joyful"],
    ["name": "Playful", "section": "Joyful"],
    ["name": "Amused", "section": "Joyful"],
    ["name": "Energetic", "section": "Joyful"],
    ["name": "Stimulating", "section": "Joyful"],
    ["name": "Vibrant", "section": "Joyful"],
    ["name": "Fascinating", "section": "Joyful"],
    ["name": "Excited", "section": "Joyful"],
    ["name": "Daring", "section": "Joyful"],
    ["name": "Scared", "section": "Scared"],
    ["name": "Anxious", "section": "Scared"],
    ["name": "Embarrassed", "section": "Scared"],
    ["name": "Insecure", "section": "Scared"],
    ["name": "Foolish", "section": "Scared"],
    ["name": "Submissive", "section": "Scared"],
    ["name": "Weak", "section": "Scared"],
    ["name": "Helpless", "section": "Scared"],
    ["name": "Insignificant", "section": "Scared"],
    ["name": "Confused", "section": "Scared"],
    ["name": "Discouraged", "section": "Scared"],
    ["name": "Rejected", "section": "Scared"],
    ["name": "Bewildered", "section": "Scared"],
    ["name": "Mad", "section": "Mad"],
    ["name": "Critical", "section": "Mad"],
    ["name": "Skeptical", "section": "Mad"],
    ["name": "Hateful", "section": "Mad"],
    ["name": "Irritated", "section": "Mad"],
    ["name": "Rage", "section": "Mad"],
    ["name": "Furious", "section": "Mad"],
    ["name": "Angry", "section": "Mad"],
    ["name": "Frustrated", "section": "Mad"],
    ["name": "Hostile", "section": "Mad"],
    ["name": "Selfish", "section": "Mad"],
    ["name": "Hurt", "section": "Mad"],
    ["name": "Jealous", "section": "Mad"],

]
