//
//  Moods.swift
//  MoodTracker
//
//  Created by Alex Wayne on 11/6/"Powerful""Powerful".
//

import Foundation

let Moods: [Mood] = [
    Mood(name: "Sad", section: "Sad"),
    Mood(name: "Despair", section: "Sad"),
    Mood(name: "Guilty", section: "Sad"),
    Mood(name: "Vulnerable", section: "Sad"),
    Mood(name: "Lonely", section: "Sad"),
    Mood(name: "Grief", section: "Sad"),
    Mood(name: "Powerless", section: "Sad"),
    Mood(name: "Remorseful", section: "Sad"),
    Mood(name: "Ashamed", section: "Sad"),
    Mood(name: "Victimized", section: "Sad"),
    Mood(name: "Fragile", section: "Sad"),
    Mood(name: "Isolated", section: "Sad"),
    Mood(name: "Abandoned", section: "Sad"),
    Mood(name: "Fearful", section: "Fearful"),
    Mood(name: "Scared", section: "Fearful"),
    Mood(name: "Anxious", section: "Fearful"),
    Mood(name: "Insecure", section: "Fearful"),
    Mood(name: "Weak", section: "Fearful"),
    Mood(name: "Helpless", section: "Fearful"),
    Mood(name: "Frightened", section: "Fearful"),
    Mood(name: "Overwhelmed", section: "Fearful"),
    Mood(name: "Worried", section: "Fearful"),
    Mood(name: "Inadequate", section: "Fearful"),
    Mood(name: "Inferior", section: "Fearful"),
    Mood(name: "Worthless", section: "Fearful"),
    Mood(name: "Insignificant", section: "Fearful"),
    Mood(name: "Disgusted", section: "Disgusted"),
    Mood(name: "Disapproving", section: "Disgusted"),
    Mood(name: "Disappointed", section: "Disgusted"),
    Mood(name: "Awful", section: "Disgusted"),
    Mood(name: "Repelled", section: "Disgusted"),
    Mood(name: "Judgmental", section: "Disgusted"),
    Mood(name: "Embarrassed", section: "Disgusted"),
    Mood(name: "Appalled", section: "Disgusted"),
    Mood(name: "Revolted", section: "Disgusted"),
    Mood(name: "Nauseated", section: "Disgusted"),
    Mood(name: "Detestable", section: "Disgusted"),
    Mood(name: "Horrified", section: "Disgusted"),
    Mood(name: "Hesitant", section: "Disgusted"),
    Mood(name: "Angry", section: "Angry"),
    Mood(name: "Humiliated", section: "Angry"),
    Mood(name: "Bitter", section: "Angry"),
    Mood(name: "Mad", section: "Angry"),
    Mood(name: "Aggressive", section: "Angry"),
    Mood(name: "Hostile", section: "Angry"),
    Mood(name: "Provoked", section: "Angry"),
    Mood(name: "Jealous", section: "Angry"),
    Mood(name: "Furious", section: "Angry"),
    Mood(name: "Violated", section: "Angry"),
    Mood(name: "Indignant", section: "Angry"),
    Mood(name: "Ridiculed", section: "Angry"),
    Mood(name: "Disrespected", section: "Angry"),
    Mood(name: "Happy", section: "Happy"),
    Mood(name: "Optimistic", section: "Happy"),
    Mood(name: "Proud", section: "Happy"),
    Mood(name: "Content", section: "Happy"),
    Mood(name: "Playful", section: "Happy"),
    Mood(name: "Inspired", section: "Happy"),
    Mood(name: "Hopeful", section: "Happy"),
    Mood(name: "Confident", section: "Happy"),
    Mood(name: "Successful", section: "Happy"),
    Mood(name: "Joyful", section: "Happy"),
    Mood(name: "Free", section: "Happy"),
    Mood(name: "Cheeky", section: "Happy"),
    Mood(name: "Aroused", section: "Happy"),
    Mood(name: "Surprised", section: "Surprised"),
    Mood(name: "Startled", section: "Surprised"),
    Mood(name: "Confused", section: "Surprised"),
    Mood(name: "Amazed", section: "Surprised"),
    Mood(name: "Excited", section: "Surprised"),
    Mood(name: "Shocked", section: "Surprised"),
    Mood(name: "Dismayed", section: "Surprised"),
    Mood(name: "Disillusioned", section: "Surprised"),
    Mood(name: "Perplexed", section: "Surprised"),
    Mood(name: "Astonished", section: "Surprised"),
    Mood(name: "Awe", section: "Surprised"),
    Mood(name: "Eager", section: "Surprised"),
    Mood(name: "Energetic", section: "Surprised"),
]
